spring:
  application:
    name: perfume-shop
  datasource:
    url: jdbc:postgresql://localhost:5432/perfume_shop
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true