server:
  port: 8080

spring:
  application:
    name: perfume-shop

  datasource:
    url: jdbc:postgresql://localhost:5432/perfume_shop
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ibrahim.alakbarov2006@gmail.com
    password: lysu snmq hvgy dbbx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 71058940819-q9fdkhb140msdgojrsmkphkhgh7ju3b7.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

app:
  whatsapp:
    business-number: 994775099979

logging:
  level:
    org.perfume: DEBUG
    org.springframework.mail: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html